import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Application } from '../applications/entities/application.entity';
import { Environment } from '../environments/entities/environment.entity';

export interface NginxEnvironmentBlock {
  applicationName: string;
  environmentName: string;
  port: number | null;
  status: string;
  serverName: string;
}

export interface NginxReport {
  generatedAt: string;
  blocks: NginxEnvironmentBlock[];
  config: string;
}

@Injectable()
export class NginxService {
  constructor(
    @InjectRepository(Application)
    private applicationsRepository: Repository<Application>,
    @InjectRepository(Environment)
    private environmentsRepository: Repository<Environment>,
  ) {}

  private toSlug(name: string): string {
    return name.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  }

  private buildServerBlock(appName: string, envName: string, port: number): string {
    const appSlug = this.toSlug(appName);
    const envSlug = this.toSlug(envName);
    return [
      `# ${appName} / ${envName}`,
      `server {`,
      `    listen 80;`,
      `    server_name ${envSlug}.${appSlug}.example.com;`,
      ``,
      `    location / {`,
      `        proxy_pass http://localhost:${port};`,
      `        proxy_http_version 1.1;`,
      `        proxy_set_header Upgrade $http_upgrade;`,
      `        proxy_set_header Connection 'upgrade';`,
      `        proxy_set_header Host $host;`,
      `        proxy_set_header X-Real-IP $remote_addr;`,
      `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
      `        proxy_set_header X-Forwarded-Proto $scheme;`,
      `        proxy_cache_bypass $http_upgrade;`,
      `    }`,
      `}`,
    ].join('\n');
  }

  async getConfig(): Promise<NginxReport> {
    const generatedAt = new Date().toISOString();

    const applications = await this.applicationsRepository.find();
    const blocks: NginxEnvironmentBlock[] = [];
    const configParts: string[] = [
      `# Nginx configuration generated by Simple Carrier`,
      `# Generated at: ${generatedAt}`,
      `# Replace "example.com" with your actual domain.`,
      ``,
    ];

    for (const app of applications) {
      const environments = await this.environmentsRepository.find({
        where: { applicationId: app.id },
        order: { createdAt: 'ASC' },
      });

      for (const env of environments) {
        const appSlug = this.toSlug(app.name);
        const envSlug = this.toSlug(env.name);
        blocks.push({
          applicationName: app.name,
          environmentName: env.name,
          port: env.port,
          status: env.status,
          serverName: `${envSlug}.${appSlug}.example.com`,
        });

        if (env.port) {
          configParts.push(this.buildServerBlock(app.name, env.name, env.port));
          configParts.push('');
        } else {
          configParts.push(`# ${app.name} / ${env.name} — not running (no port assigned)`);
          configParts.push('');
        }
      }
    }

    return {
      generatedAt,
      blocks,
      config: configParts.join('\n'),
    };
  }
}
